---
# This is for the whole project and we allow some extra stuff in tests
root: true
extends: eslint:recommended
env:
  es6: true
  commonjs: true
rules:
  no-cond-assign: off
  no-useless-escape: off
  no-unused-vars:
    - error
    - args: none
